version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fuel-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=example;Database=FuelDatabase
      - REDIS_HOST=redis:6379
    depends_on:
      - db
    command: ["./start.sh"]  # Hier wird das Skript ausgeführt
    networks:
      - fuel-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
    networks:
      - fuel-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: FuelDatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Dies exponiert den Port 5432 für den Host
    networks:
      - fuel-network

networks:
  fuel-network:
    driver: bridge

volumes:
  postgres-data:
  redis_data:
